version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies]
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [dependencies]
    groups:
      compatible-updates:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /.github/linters
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies]
  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    labels: [dependencies]
