[package]
name = "opencrate-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "opencrate"
path = "src/main.rs"

[dependencies]
opencrate-core = { workspace = true }
opencrate-aura = { workspace = true }
opencrate-fan = { workspace = true }
clap = { version = "4", features = ["derive"] }
